services:
    ds.account.event.listener.locale:
        class: Ds\Bundle\AccountBundle\Event\Listener\LocaleListener
        arguments:
            - @request_stack
            - @translator
        tags:
            - { name: kernel.event_listener, event: kernel.request }
